package:
  format-version: "1.0.0"
  name: "crypto_v4"
  type: "api"
  status: "production"
  required: false
  version: "v4.0.0-TC1"

  dependencies:
    - name: "core"
      type: "package"
      version: "v3.13.1"
    - name: "wolfssl"
      type: "package"
      version: "v5.7.0-stable"
    - name: "zlib"
      type: "package"
      version: "v1.2.11"
