package:
  format-version: "1.0.0"
  name: "crypto_v4"
  type: "api"
  status: "production"
  required: false
  version: "v4.0.0-E3"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.21.0"
    - name: "wolfssl"
      type: "package"
      version: "v5.7.0"
